### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by TahjDev** [stellalc7/fullstack-proj#2]
The associations should also be bullets
Can a pin not belong to more than one board? should there be a joins table in between? so a pin can have many boards and vice versa?
Can you also follow boards? 
Should pins have names and should the pins table also have a saver_id? And if the pins have names and you're going to search by those names or if you're going to search by board titles? then it should be indexed for lookup time

**Comment by stellalc7** [comment]
- Associations are bulleted
- Joins table created. Yes, a pin can have many boards, and vice versa
- No, in my clone a user cannot follow boards, just other users for now
- `pins` table now have `title`
- `saver_id` omitted from pins, since I will have the `saves` joins table
- `pins` and `boards` tables now indexed on title for search
